// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CoralSession {
  final String accessToken;
  final String? naId;
  final String? coralUserId;
  final DateTime? expiresAt;
  final String nickname;
  final String? avatarUrl;
  final Uint8List? avatarBytes;

  const CoralSession({
    required this.accessToken,
    this.naId,
    this.coralUserId,
    this.expiresAt,
    required this.nickname,
    this.avatarUrl,
    this.avatarBytes,
  });

  @override
  int get hashCode =>
      accessToken.hashCode ^
      naId.hashCode ^
      coralUserId.hashCode ^
      expiresAt.hashCode ^
      nickname.hashCode ^
      avatarUrl.hashCode ^
      avatarBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoralSession &&
          runtimeType == other.runtimeType &&
          accessToken == other.accessToken &&
          naId == other.naId &&
          coralUserId == other.coralUserId &&
          expiresAt == other.expiresAt &&
          nickname == other.nickname &&
          avatarUrl == other.avatarUrl &&
          avatarBytes == other.avatarBytes;
}
