// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'nso/provider.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'settings.dart';

// These functions are ignored because they are not marked as `pub`: `core`, `error_text`

Future<void> initCore({required String libraryRoot}) =>
    RustLib.instance.api.crateBridgeInitCore(libraryRoot: libraryRoot);

Future<AppSettings?> loadSettings() =>
    RustLib.instance.api.crateBridgeLoadSettings();

Future<void> saveSettings({required AppSettings settings}) =>
    RustLib.instance.api.crateBridgeSaveSettings(settings: settings);

Future<void> saveSyncPolicy({required SyncPolicy policy}) =>
    RustLib.instance.api.crateBridgeSaveSyncPolicy(policy: policy);

Future<SyncScheduleStatus> syncScheduleStatus({required String accountId}) =>
    RustLib.instance.api.crateBridgeSyncScheduleStatus(accountId: accountId);

Future<SyncScheduleStatus> recordSyncOutcome({
  required String accountId,
  required bool foundNewMedia,
}) => RustLib.instance.api.crateBridgeRecordSyncOutcome(
  accountId: accountId,
  foundNewMedia: foundNewMedia,
);

Future<SyncRuntimeState> syncAccountHistory({required String accountId}) =>
    RustLib.instance.api.crateBridgeSyncAccountHistory(accountId: accountId);

Future<SyncRuntimeState> recordSyncAttempt({
  required String accountId,
  required String status,
  required BigInt totalFound,
  required BigInt downloaded,
  required BigInt duplicates,
  required BigInt failed,
}) => RustLib.instance.api.crateBridgeRecordSyncAttempt(
  accountId: accountId,
  status: status,
  totalFound: totalFound,
  downloaded: downloaded,
  duplicates: duplicates,
  failed: failed,
);

Future<LoginChallenge> createNintendoLoginChallenge({String? proxyUrl}) =>
    RustLib.instance.api.crateBridgeCreateNintendoLoginChallenge(
      proxyUrl: proxyUrl,
    );

Future<String> exchangeNintendoCallback({
  required String callbackUrl,
  required String expectedState,
  required String verifier,
  String? proxyUrl,
}) => RustLib.instance.api.crateBridgeExchangeNintendoCallback(
  callbackUrl: callbackUrl,
  expectedState: expectedState,
  verifier: verifier,
  proxyUrl: proxyUrl,
);

Future<CoralSession> establishCoralSession({
  required String sessionToken,
  String? proxyUrl,
}) => RustLib.instance.api.crateBridgeEstablishCoralSession(
  sessionToken: sessionToken,
  proxyUrl: proxyUrl,
);

Future<SyncSummary> syncNso({
  required CoralSession session,
  String? proxyUrl,
}) => RustLib.instance.api.crateBridgeSyncNso(
  session: session,
  proxyUrl: proxyUrl,
);

Future<bool> cancelCurrentSync() =>
    RustLib.instance.api.crateBridgeCancelCurrentSync();

Future<SyncProgress?> currentSyncProgress() =>
    RustLib.instance.api.crateBridgeCurrentSyncProgress();

Future<List<MediaAsset>> listMedia({required GalleryQuery query}) =>
    RustLib.instance.api.crateBridgeListMedia(query: query);

Future<List<AlbumSummary>> listAlbums() =>
    RustLib.instance.api.crateBridgeListAlbums();

Future<List<String>> listTags() => RustLib.instance.api.crateBridgeListTags();

Future<List<TagUsageSummary>> listTagUsage() =>
    RustLib.instance.api.crateBridgeListTagUsage();

Future<PlatformInt64> createTag({required String name}) =>
    RustLib.instance.api.crateBridgeCreateTag(name: name);

Future<void> renameTag({
  required PlatformInt64 tagId,
  required String newName,
}) => RustLib.instance.api.crateBridgeRenameTag(tagId: tagId, newName: newName);

Future<void> deleteTag({required PlatformInt64 tagId}) =>
    RustLib.instance.api.crateBridgeDeleteTag(tagId: tagId);

Future<void> mergeTags({
  required Int64List tagIds,
  required String targetName,
}) => RustLib.instance.api.crateBridgeMergeTags(
  tagIds: tagIds,
  targetName: targetName,
);

Future<List<GameTagSummary>> listGameTags() =>
    RustLib.instance.api.crateBridgeListGameTags();

Future<List<GameTagAliasSummary>> listGameTagAliases() =>
    RustLib.instance.api.crateBridgeListGameTagAliases();

Future<void> recordGameTagSelection({required String gameName}) =>
    RustLib.instance.api.crateBridgeRecordGameTagSelection(gameName: gameName);

Future<void> mergeGameTags({
  required List<String> gameNames,
  required String targetName,
}) => RustLib.instance.api.crateBridgeMergeGameTags(
  gameNames: gameNames,
  targetName: targetName,
);

Future<void> renameGameTag({
  required String gameName,
  required String targetName,
}) => RustLib.instance.api.crateBridgeRenameGameTag(
  gameName: gameName,
  targetName: targetName,
);

Future<ImportSummary> importLocalFiles({required List<String> paths}) =>
    RustLib.instance.api.crateBridgeImportLocalFiles(paths: paths);

Future<ImportSummary> importCustomFiles({
  required List<String> paths,
  required String gameName,
}) => RustLib.instance.api.crateBridgeImportCustomFiles(
  paths: paths,
  gameName: gameName,
);

Future<ImportSummary> importMtpFiles({
  required List<String> paths,
  required String deviceName,
}) => RustLib.instance.api.crateBridgeImportMtpFiles(
  paths: paths,
  deviceName: deviceName,
);

Future<MediaExportSummary> exportMedia({
  required Int64List mediaIds,
  required String destination,
  required String nameFormat,
}) => RustLib.instance.api.crateBridgeExportMedia(
  mediaIds: mediaIds,
  destination: destination,
  nameFormat: nameFormat,
);

Future<MediaAsset> commitVideoEdit({
  required PlatformInt64 mediaId,
  required String processedPath,
  required bool overwrite,
}) => RustLib.instance.api.crateBridgeCommitVideoEdit(
  mediaId: mediaId,
  processedPath: processedPath,
  overwrite: overwrite,
);

Future<MediaAsset> saveVideoFrame({
  required PlatformInt64 mediaId,
  required List<int> bytes,
  required String extension_,
}) => RustLib.instance.api.crateBridgeSaveVideoFrame(
  mediaId: mediaId,
  bytes: bytes,
  extension_: extension_,
);

Future<MediaAsset> commitMergedVideo({
  required Int64List mediaIds,
  required String processedPath,
}) => RustLib.instance.api.crateBridgeCommitMergedVideo(
  mediaIds: mediaIds,
  processedPath: processedPath,
);

Future<void> setFavorite({
  required PlatformInt64 mediaId,
  required bool favorite,
}) => RustLib.instance.api.crateBridgeSetFavorite(
  mediaId: mediaId,
  favorite: favorite,
);

Future<void> setNote({required PlatformInt64 mediaId, required String note}) =>
    RustLib.instance.api.crateBridgeSetNote(mediaId: mediaId, note: note);

Future<PlatformInt64> addTag({
  required PlatformInt64 mediaId,
  required String tag,
}) => RustLib.instance.api.crateBridgeAddTag(mediaId: mediaId, tag: tag);

Future<void> replaceTags({
  required PlatformInt64 mediaId,
  required List<String> tags,
}) => RustLib.instance.api.crateBridgeReplaceTags(mediaId: mediaId, tags: tags);

Future<PlatformInt64> createAlbum({
  required String name,
  required String description,
  required bool smart,
}) => RustLib.instance.api.crateBridgeCreateAlbum(
  name: name,
  description: description,
  smart: smart,
);

Future<void> updateAlbum({
  required PlatformInt64 albumId,
  required String name,
  required String description,
  required bool smart,
}) => RustLib.instance.api.crateBridgeUpdateAlbum(
  albumId: albumId,
  name: name,
  description: description,
  smart: smart,
);

Future<List<AlbumRule>> listAlbumRules({required PlatformInt64 albumId}) =>
    RustLib.instance.api.crateBridgeListAlbumRules(albumId: albumId);

Future<void> deleteAlbum({required PlatformInt64 albumId}) =>
    RustLib.instance.api.crateBridgeDeleteAlbum(albumId: albumId);

Future<void> replaceAlbumRules({
  required PlatformInt64 albumId,
  required List<AlbumRule> rules,
}) => RustLib.instance.api.crateBridgeReplaceAlbumRules(
  albumId: albumId,
  rules: rules,
);

Future<void> addMediaToAlbum({
  required PlatformInt64 albumId,
  required PlatformInt64 mediaId,
}) => RustLib.instance.api.crateBridgeAddMediaToAlbum(
  albumId: albumId,
  mediaId: mediaId,
);

Future<MediaDeletionResult> deleteMedia({required PlatformInt64 mediaId}) =>
    RustLib.instance.api.crateBridgeDeleteMedia(mediaId: mediaId);

Future<MediaDeletionResult> removeMediaFromAlbum({
  required PlatformInt64 albumId,
  required PlatformInt64 mediaId,
}) => RustLib.instance.api.crateBridgeRemoveMediaFromAlbum(
  albumId: albumId,
  mediaId: mediaId,
);

Future<LibraryRelocationResult> relocateMediaLibrary({
  required AppSettings settings,
}) => RustLib.instance.api.crateBridgeRelocateMediaLibrary(settings: settings);
