// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'bridge.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';
import 'models.dart';
import 'nso/provider.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

import 'settings.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AlbumRule dco_decode_album_rule(dynamic raw);

  @protected
  AlbumSummary dco_decode_album_summary(dynamic raw);

  @protected
  AppSettings dco_decode_app_settings(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw);

  @protected
  CoralSession dco_decode_box_autoadd_coral_session(dynamic raw);

  @protected
  GalleryQuery dco_decode_box_autoadd_gallery_query(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  SyncAttemptSummary dco_decode_box_autoadd_sync_attempt_summary(dynamic raw);

  @protected
  SyncPolicy dco_decode_box_autoadd_sync_policy(dynamic raw);

  @protected
  SyncProgress dco_decode_box_autoadd_sync_progress(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CoralSession dco_decode_coral_session(dynamic raw);

  @protected
  GalleryKindFilter dco_decode_gallery_kind_filter(dynamic raw);

  @protected
  GalleryQuery dco_decode_gallery_query(dynamic raw);

  @protected
  GameTagAliasSummary dco_decode_game_tag_alias_summary(dynamic raw);

  @protected
  GameTagSummary dco_decode_game_tag_summary(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportItemError dco_decode_import_item_error(dynamic raw);

  @protected
  ImportSummary dco_decode_import_summary(dynamic raw);

  @protected
  LibraryRelocationResult dco_decode_library_relocation_result(dynamic raw);

  @protected
  LibraryRootProbe dco_decode_library_root_probe(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AlbumRule> dco_decode_list_album_rule(dynamic raw);

  @protected
  List<AlbumSummary> dco_decode_list_album_summary(dynamic raw);

  @protected
  List<GameTagAliasSummary> dco_decode_list_game_tag_alias_summary(dynamic raw);

  @protected
  List<GameTagSummary> dco_decode_list_game_tag_summary(dynamic raw);

  @protected
  List<ImportItemError> dco_decode_list_import_item_error(dynamic raw);

  @protected
  List<MediaAsset> dco_decode_list_media_asset(dynamic raw);

  @protected
  List<MediaExportItemError> dco_decode_list_media_export_item_error(
    dynamic raw,
  );

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SyncItemError> dco_decode_list_sync_item_error(dynamic raw);

  @protected
  List<TagUsageSummary> dco_decode_list_tag_usage_summary(dynamic raw);

  @protected
  LoginChallenge dco_decode_login_challenge(dynamic raw);

  @protected
  MediaAsset dco_decode_media_asset(dynamic raw);

  @protected
  MediaDeletionResult dco_decode_media_deletion_result(dynamic raw);

  @protected
  MediaExportItemError dco_decode_media_export_item_error(dynamic raw);

  @protected
  MediaExportSummary dco_decode_media_export_summary(dynamic raw);

  @protected
  MediaKind dco_decode_media_kind(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  AppSettings? dco_decode_opt_box_autoadd_app_settings(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  SyncAttemptSummary? dco_decode_opt_box_autoadd_sync_attempt_summary(
    dynamic raw,
  );

  @protected
  SyncProgress? dco_decode_opt_box_autoadd_sync_progress(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  SyncAttemptSummary dco_decode_sync_attempt_summary(dynamic raw);

  @protected
  SyncItemError dco_decode_sync_item_error(dynamic raw);

  @protected
  SyncPolicy dco_decode_sync_policy(dynamic raw);

  @protected
  SyncProgress dco_decode_sync_progress(dynamic raw);

  @protected
  SyncRuntimeState dco_decode_sync_runtime_state(dynamic raw);

  @protected
  SyncScheduleStatus dco_decode_sync_schedule_status(dynamic raw);

  @protected
  SyncSummary dco_decode_sync_summary(dynamic raw);

  @protected
  TagUsageSummary dco_decode_tag_usage_summary(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AlbumRule sse_decode_album_rule(SseDeserializer deserializer);

  @protected
  AlbumSummary sse_decode_album_summary(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  CoralSession sse_decode_box_autoadd_coral_session(
    SseDeserializer deserializer,
  );

  @protected
  GalleryQuery sse_decode_box_autoadd_gallery_query(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SyncAttemptSummary sse_decode_box_autoadd_sync_attempt_summary(
    SseDeserializer deserializer,
  );

  @protected
  SyncPolicy sse_decode_box_autoadd_sync_policy(SseDeserializer deserializer);

  @protected
  SyncProgress sse_decode_box_autoadd_sync_progress(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CoralSession sse_decode_coral_session(SseDeserializer deserializer);

  @protected
  GalleryKindFilter sse_decode_gallery_kind_filter(
    SseDeserializer deserializer,
  );

  @protected
  GalleryQuery sse_decode_gallery_query(SseDeserializer deserializer);

  @protected
  GameTagAliasSummary sse_decode_game_tag_alias_summary(
    SseDeserializer deserializer,
  );

  @protected
  GameTagSummary sse_decode_game_tag_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportItemError sse_decode_import_item_error(SseDeserializer deserializer);

  @protected
  ImportSummary sse_decode_import_summary(SseDeserializer deserializer);

  @protected
  LibraryRelocationResult sse_decode_library_relocation_result(
    SseDeserializer deserializer,
  );

  @protected
  LibraryRootProbe sse_decode_library_root_probe(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AlbumRule> sse_decode_list_album_rule(SseDeserializer deserializer);

  @protected
  List<AlbumSummary> sse_decode_list_album_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<GameTagAliasSummary> sse_decode_list_game_tag_alias_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<GameTagSummary> sse_decode_list_game_tag_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<ImportItemError> sse_decode_list_import_item_error(
    SseDeserializer deserializer,
  );

  @protected
  List<MediaAsset> sse_decode_list_media_asset(SseDeserializer deserializer);

  @protected
  List<MediaExportItemError> sse_decode_list_media_export_item_error(
    SseDeserializer deserializer,
  );

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SyncItemError> sse_decode_list_sync_item_error(
    SseDeserializer deserializer,
  );

  @protected
  List<TagUsageSummary> sse_decode_list_tag_usage_summary(
    SseDeserializer deserializer,
  );

  @protected
  LoginChallenge sse_decode_login_challenge(SseDeserializer deserializer);

  @protected
  MediaAsset sse_decode_media_asset(SseDeserializer deserializer);

  @protected
  MediaDeletionResult sse_decode_media_deletion_result(
    SseDeserializer deserializer,
  );

  @protected
  MediaExportItemError sse_decode_media_export_item_error(
    SseDeserializer deserializer,
  );

  @protected
  MediaExportSummary sse_decode_media_export_summary(
    SseDeserializer deserializer,
  );

  @protected
  MediaKind sse_decode_media_kind(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  AppSettings? sse_decode_opt_box_autoadd_app_settings(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SyncAttemptSummary? sse_decode_opt_box_autoadd_sync_attempt_summary(
    SseDeserializer deserializer,
  );

  @protected
  SyncProgress? sse_decode_opt_box_autoadd_sync_progress(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  SyncAttemptSummary sse_decode_sync_attempt_summary(
    SseDeserializer deserializer,
  );

  @protected
  SyncItemError sse_decode_sync_item_error(SseDeserializer deserializer);

  @protected
  SyncPolicy sse_decode_sync_policy(SseDeserializer deserializer);

  @protected
  SyncProgress sse_decode_sync_progress(SseDeserializer deserializer);

  @protected
  SyncRuntimeState sse_decode_sync_runtime_state(SseDeserializer deserializer);

  @protected
  SyncScheduleStatus sse_decode_sync_schedule_status(
    SseDeserializer deserializer,
  );

  @protected
  SyncSummary sse_decode_sync_summary(SseDeserializer deserializer);

  @protected
  TagUsageSummary sse_decode_tag_usage_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_album_rule(AlbumRule self, SseSerializer serializer);

  @protected
  void sse_encode_album_summary(AlbumSummary self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
    DateTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_app_settings(
    AppSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_coral_session(
    CoralSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_gallery_query(
    GalleryQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_attempt_summary(
    SyncAttemptSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_policy(
    SyncPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_progress(
    SyncProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_coral_session(CoralSession self, SseSerializer serializer);

  @protected
  void sse_encode_gallery_kind_filter(
    GalleryKindFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gallery_query(GalleryQuery self, SseSerializer serializer);

  @protected
  void sse_encode_game_tag_alias_summary(
    GameTagAliasSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_game_tag_summary(
    GameTagSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_item_error(
    ImportItemError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_import_summary(ImportSummary self, SseSerializer serializer);

  @protected
  void sse_encode_library_relocation_result(
    LibraryRelocationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_library_root_probe(
    LibraryRootProbe self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_album_rule(
    List<AlbumRule> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_album_summary(
    List<AlbumSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_game_tag_alias_summary(
    List<GameTagAliasSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_game_tag_summary(
    List<GameTagSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_import_item_error(
    List<ImportItemError> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_media_asset(
    List<MediaAsset> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_media_export_item_error(
    List<MediaExportItemError> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sync_item_error(
    List<SyncItemError> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tag_usage_summary(
    List<TagUsageSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_login_challenge(
    LoginChallenge self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_asset(MediaAsset self, SseSerializer serializer);

  @protected
  void sse_encode_media_deletion_result(
    MediaDeletionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_export_item_error(
    MediaExportItemError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_export_summary(
    MediaExportSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_kind(MediaKind self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
    DateTime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_app_settings(
    AppSettings? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_attempt_summary(
    SyncAttemptSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_progress(
    SyncProgress? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_attempt_summary(
    SyncAttemptSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_item_error(SyncItemError self, SseSerializer serializer);

  @protected
  void sse_encode_sync_policy(SyncPolicy self, SseSerializer serializer);

  @protected
  void sse_encode_sync_progress(SyncProgress self, SseSerializer serializer);

  @protected
  void sse_encode_sync_runtime_state(
    SyncRuntimeState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_schedule_status(
    SyncScheduleStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_summary(SyncSummary self, SseSerializer serializer);

  @protected
  void sse_encode_tag_usage_summary(
    TagUsageSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
