// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AlbumRule {
  final PlatformInt64 ruleGroup;
  final String field;
  final String operator_;
  final String value;

  const AlbumRule({
    required this.ruleGroup,
    required this.field,
    required this.operator_,
    required this.value,
  });

  @override
  int get hashCode =>
      ruleGroup.hashCode ^ field.hashCode ^ operator_.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumRule &&
          runtimeType == other.runtimeType &&
          ruleGroup == other.ruleGroup &&
          field == other.field &&
          operator_ == other.operator_ &&
          value == other.value;
}

class AlbumSummary {
  final PlatformInt64 id;
  final String name;
  final String description;
  final String albumType;
  final bool pinned;
  final String? systemKey;
  final BigInt mediaCount;

  const AlbumSummary({
    required this.id,
    required this.name,
    required this.description,
    required this.albumType,
    required this.pinned,
    this.systemKey,
    required this.mediaCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      albumType.hashCode ^
      pinned.hashCode ^
      systemKey.hashCode ^
      mediaCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          albumType == other.albumType &&
          pinned == other.pinned &&
          systemKey == other.systemKey &&
          mediaCount == other.mediaCount;
}

enum GalleryKindFilter { all, image, video }

class GalleryQuery {
  final GalleryKindFilter kind;
  final int limit;
  final int offset;
  final bool favoriteOnly;
  final PlatformInt64? albumId;
  final bool newestFirst;
  final List<String> gameNames;
  final DateTime? capturedFrom;
  final DateTime? capturedUntil;

  const GalleryQuery({
    required this.kind,
    required this.limit,
    required this.offset,
    required this.favoriteOnly,
    this.albumId,
    required this.newestFirst,
    required this.gameNames,
    this.capturedFrom,
    this.capturedUntil,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      limit.hashCode ^
      offset.hashCode ^
      favoriteOnly.hashCode ^
      albumId.hashCode ^
      newestFirst.hashCode ^
      gameNames.hashCode ^
      capturedFrom.hashCode ^
      capturedUntil.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryQuery &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          limit == other.limit &&
          offset == other.offset &&
          favoriteOnly == other.favoriteOnly &&
          albumId == other.albumId &&
          newestFirst == other.newestFirst &&
          gameNames == other.gameNames &&
          capturedFrom == other.capturedFrom &&
          capturedUntil == other.capturedUntil;
}

class GameTagAliasSummary {
  final String sourceName;
  final String targetName;

  const GameTagAliasSummary({
    required this.sourceName,
    required this.targetName,
  });

  @override
  int get hashCode => sourceName.hashCode ^ targetName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameTagAliasSummary &&
          runtimeType == other.runtimeType &&
          sourceName == other.sourceName &&
          targetName == other.targetName;
}

class GameTagSummary {
  final String name;
  final BigInt imageCount;
  final BigInt videoCount;
  final BigInt selectionCount;

  const GameTagSummary({
    required this.name,
    required this.imageCount,
    required this.videoCount,
    required this.selectionCount,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      imageCount.hashCode ^
      videoCount.hashCode ^
      selectionCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameTagSummary &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          imageCount == other.imageCount &&
          videoCount == other.videoCount &&
          selectionCount == other.selectionCount;
}

class ImportItemError {
  final String path;
  final String message;

  const ImportItemError({required this.path, required this.message});

  @override
  int get hashCode => path.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportItemError &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          message == other.message;
}

class ImportSummary {
  final BigInt totalFound;
  final BigInt imported;
  final BigInt duplicates;
  final BigInt failed;
  final List<ImportItemError> errors;

  const ImportSummary({
    required this.totalFound,
    required this.imported,
    required this.duplicates,
    required this.failed,
    required this.errors,
  });

  @override
  int get hashCode =>
      totalFound.hashCode ^
      imported.hashCode ^
      duplicates.hashCode ^
      failed.hashCode ^
      errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportSummary &&
          runtimeType == other.runtimeType &&
          totalFound == other.totalFound &&
          imported == other.imported &&
          duplicates == other.duplicates &&
          failed == other.failed &&
          errors == other.errors;
}

class LibraryRelocationResult {
  final BigInt movedFiles;
  final String libraryPath;

  const LibraryRelocationResult({
    required this.movedFiles,
    required this.libraryPath,
  });

  @override
  int get hashCode => movedFiles.hashCode ^ libraryPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryRelocationResult &&
          runtimeType == other.runtimeType &&
          movedFiles == other.movedFiles &&
          libraryPath == other.libraryPath;
}

class LoginChallenge {
  final String authorizationUrl;
  final String state;
  final String verifier;

  const LoginChallenge({
    required this.authorizationUrl,
    required this.state,
    required this.verifier,
  });

  @override
  int get hashCode =>
      authorizationUrl.hashCode ^ state.hashCode ^ verifier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginChallenge &&
          runtimeType == other.runtimeType &&
          authorizationUrl == other.authorizationUrl &&
          state == other.state &&
          verifier == other.verifier;
}

class MediaAsset {
  final PlatformInt64 id;
  final String sha256;
  final String originalName;
  final String storagePath;
  final MediaKind kind;
  final DateTime? capturedAt;
  final DateTime importedAt;
  final String? gameTitleId;
  final String gameName;
  final bool favorite;
  final String? note;
  final List<String> tags;

  const MediaAsset({
    required this.id,
    required this.sha256,
    required this.originalName,
    required this.storagePath,
    required this.kind,
    this.capturedAt,
    required this.importedAt,
    this.gameTitleId,
    required this.gameName,
    required this.favorite,
    this.note,
    required this.tags,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sha256.hashCode ^
      originalName.hashCode ^
      storagePath.hashCode ^
      kind.hashCode ^
      capturedAt.hashCode ^
      importedAt.hashCode ^
      gameTitleId.hashCode ^
      gameName.hashCode ^
      favorite.hashCode ^
      note.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaAsset &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sha256 == other.sha256 &&
          originalName == other.originalName &&
          storagePath == other.storagePath &&
          kind == other.kind &&
          capturedAt == other.capturedAt &&
          importedAt == other.importedAt &&
          gameTitleId == other.gameTitleId &&
          gameName == other.gameName &&
          favorite == other.favorite &&
          note == other.note &&
          tags == other.tags;
}

class MediaDeletionResult {
  final bool removedFromAlbum;
  final bool deletedFromLibrary;
  final BigInt remainingAlbumCount;

  const MediaDeletionResult({
    required this.removedFromAlbum,
    required this.deletedFromLibrary,
    required this.remainingAlbumCount,
  });

  @override
  int get hashCode =>
      removedFromAlbum.hashCode ^
      deletedFromLibrary.hashCode ^
      remainingAlbumCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaDeletionResult &&
          runtimeType == other.runtimeType &&
          removedFromAlbum == other.removedFromAlbum &&
          deletedFromLibrary == other.deletedFromLibrary &&
          remainingAlbumCount == other.remainingAlbumCount;
}

class MediaExportItemError {
  final PlatformInt64 mediaId;
  final String name;
  final String message;

  const MediaExportItemError({
    required this.mediaId,
    required this.name,
    required this.message,
  });

  @override
  int get hashCode => mediaId.hashCode ^ name.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaExportItemError &&
          runtimeType == other.runtimeType &&
          mediaId == other.mediaId &&
          name == other.name &&
          message == other.message;
}

class MediaExportSummary {
  final BigInt total;
  final BigInt exported;
  final BigInt failed;
  final List<MediaExportItemError> errors;

  const MediaExportSummary({
    required this.total,
    required this.exported,
    required this.failed,
    required this.errors,
  });

  @override
  int get hashCode =>
      total.hashCode ^ exported.hashCode ^ failed.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaExportSummary &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          exported == other.exported &&
          failed == other.failed &&
          errors == other.errors;
}

enum MediaKind { image, video }

class SyncItemError {
  final String? remoteId;
  final String message;

  const SyncItemError({this.remoteId, required this.message});

  @override
  int get hashCode => remoteId.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncItemError &&
          runtimeType == other.runtimeType &&
          remoteId == other.remoteId &&
          message == other.message;
}

class SyncProgress {
  final String jobId;
  final String status;
  final BigInt totalItems;
  final BigInt processedItems;
  final BigInt synchronizedItems;
  final BigInt failedItems;

  const SyncProgress({
    required this.jobId,
    required this.status,
    required this.totalItems,
    required this.processedItems,
    required this.synchronizedItems,
    required this.failedItems,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      status.hashCode ^
      totalItems.hashCode ^
      processedItems.hashCode ^
      synchronizedItems.hashCode ^
      failedItems.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncProgress &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          status == other.status &&
          totalItems == other.totalItems &&
          processedItems == other.processedItems &&
          synchronizedItems == other.synchronizedItems &&
          failedItems == other.failedItems;
}

class SyncSummary {
  final String jobId;
  final BigInt totalFound;
  final BigInt downloaded;
  final BigInt duplicates;
  final BigInt skippedRemote;
  final BigInt failed;
  final DateTime? newMediaAt;
  final String? cursor;
  final List<SyncItemError> errors;

  const SyncSummary({
    required this.jobId,
    required this.totalFound,
    required this.downloaded,
    required this.duplicates,
    required this.skippedRemote,
    required this.failed,
    this.newMediaAt,
    this.cursor,
    required this.errors,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      totalFound.hashCode ^
      downloaded.hashCode ^
      duplicates.hashCode ^
      skippedRemote.hashCode ^
      failed.hashCode ^
      newMediaAt.hashCode ^
      cursor.hashCode ^
      errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncSummary &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          totalFound == other.totalFound &&
          downloaded == other.downloaded &&
          duplicates == other.duplicates &&
          skippedRemote == other.skippedRemote &&
          failed == other.failed &&
          newMediaAt == other.newMediaAt &&
          cursor == other.cursor &&
          errors == other.errors;
}

class TagUsageSummary {
  final PlatformInt64 id;
  final String name;
  final BigInt imageCount;
  final BigInt videoCount;

  const TagUsageSummary({
    required this.id,
    required this.name,
    required this.imageCount,
    required this.videoCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ imageCount.hashCode ^ videoCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagUsageSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          imageCount == other.imageCount &&
          videoCount == other.videoCount;
}
