// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AppSettings {
  final String? proxyUrl;
  final String libraryPath;
  final String theme;
  final String language;
  final int galleryColumns;
  final int galleryRows;
  final bool showNotePreview;
  final bool showGameTag;
  final bool compactTagDisplay;
  final bool autoPlayVideo;
  final bool autoSyncOnLaunch;
  final String closeBehavior;
  final List<String> customFontPaths;
  final SyncPolicy syncPolicy;

  const AppSettings({
    this.proxyUrl,
    required this.libraryPath,
    required this.theme,
    required this.language,
    required this.galleryColumns,
    required this.galleryRows,
    required this.showNotePreview,
    required this.showGameTag,
    required this.compactTagDisplay,
    required this.autoPlayVideo,
    required this.autoSyncOnLaunch,
    required this.closeBehavior,
    required this.customFontPaths,
    required this.syncPolicy,
  });

  @override
  int get hashCode =>
      proxyUrl.hashCode ^
      libraryPath.hashCode ^
      theme.hashCode ^
      language.hashCode ^
      galleryColumns.hashCode ^
      galleryRows.hashCode ^
      showNotePreview.hashCode ^
      showGameTag.hashCode ^
      compactTagDisplay.hashCode ^
      autoPlayVideo.hashCode ^
      autoSyncOnLaunch.hashCode ^
      closeBehavior.hashCode ^
      customFontPaths.hashCode ^
      syncPolicy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          proxyUrl == other.proxyUrl &&
          libraryPath == other.libraryPath &&
          theme == other.theme &&
          language == other.language &&
          galleryColumns == other.galleryColumns &&
          galleryRows == other.galleryRows &&
          showNotePreview == other.showNotePreview &&
          showGameTag == other.showGameTag &&
          compactTagDisplay == other.compactTagDisplay &&
          autoPlayVideo == other.autoPlayVideo &&
          autoSyncOnLaunch == other.autoSyncOnLaunch &&
          closeBehavior == other.closeBehavior &&
          customFontPaths == other.customFontPaths &&
          syncPolicy == other.syncPolicy;
}

class SyncAttemptSummary {
  final DateTime attemptedAt;
  final String status;
  final BigInt totalFound;
  final BigInt downloaded;
  final BigInt duplicates;
  final BigInt failed;

  const SyncAttemptSummary({
    required this.attemptedAt,
    required this.status,
    required this.totalFound,
    required this.downloaded,
    required this.duplicates,
    required this.failed,
  });

  @override
  int get hashCode =>
      attemptedAt.hashCode ^
      status.hashCode ^
      totalFound.hashCode ^
      downloaded.hashCode ^
      duplicates.hashCode ^
      failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncAttemptSummary &&
          runtimeType == other.runtimeType &&
          attemptedAt == other.attemptedAt &&
          status == other.status &&
          totalFound == other.totalFound &&
          downloaded == other.downloaded &&
          duplicates == other.duplicates &&
          failed == other.failed;
}

class SyncPolicy {
  final bool enabled;
  final int activeIntervalMinutes;
  final int sleepAfterHours;

  const SyncPolicy({
    required this.enabled,
    required this.activeIntervalMinutes,
    required this.sleepAfterHours,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      activeIntervalMinutes.hashCode ^
      sleepAfterHours.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncPolicy &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          activeIntervalMinutes == other.activeIntervalMinutes &&
          sleepAfterHours == other.sleepAfterHours;
}

class SyncRuntimeState {
  final DateTime? lastSuccessfulSyncAt;
  final DateTime? lastNewMediaAt;
  final SyncAttemptSummary? latestAttempt;

  const SyncRuntimeState({
    this.lastSuccessfulSyncAt,
    this.lastNewMediaAt,
    this.latestAttempt,
  });

  @override
  int get hashCode =>
      lastSuccessfulSyncAt.hashCode ^
      lastNewMediaAt.hashCode ^
      latestAttempt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncRuntimeState &&
          runtimeType == other.runtimeType &&
          lastSuccessfulSyncAt == other.lastSuccessfulSyncAt &&
          lastNewMediaAt == other.lastNewMediaAt &&
          latestAttempt == other.latestAttempt;
}

class SyncScheduleStatus {
  final DateTime? lastSuccessfulSyncAt;
  final DateTime? lastNewMediaAt;
  final bool sleeping;
  final int? intervalMinutes;
  final DateTime? nextSyncAt;

  const SyncScheduleStatus({
    this.lastSuccessfulSyncAt,
    this.lastNewMediaAt,
    required this.sleeping,
    this.intervalMinutes,
    this.nextSyncAt,
  });

  @override
  int get hashCode =>
      lastSuccessfulSyncAt.hashCode ^
      lastNewMediaAt.hashCode ^
      sleeping.hashCode ^
      intervalMinutes.hashCode ^
      nextSyncAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncScheduleStatus &&
          runtimeType == other.runtimeType &&
          lastSuccessfulSyncAt == other.lastSuccessfulSyncAt &&
          lastNewMediaAt == other.lastNewMediaAt &&
          sleeping == other.sleeping &&
          intervalMinutes == other.intervalMinutes &&
          nextSyncAt == other.nextSyncAt;
}
